name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: |
          npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: npm run make

      - name: Publish Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish

      # Install AWS CLI on Windows
      - name: Install AWS CLI on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "Downloading AWS CLI MSI installer..."
          Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
          Write-Host "Installing AWS CLI..."
          Start-Process msiexec.exe -ArgumentList '/i AWSCLIV2.msi /quiet /qn' -NoNewWindow -Wait
          Write-Host "AWS CLI installed successfully."

      # Install AWS CLI on macOS and Linux
      - name: Install AWS CLI on macOS and Linux
        if: matrix.os == 'macos-latest'
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg AWSCLIV2.pkg -target /
          aws --version

      # Verify AWS CLI Installation
      - name: Verify AWS CLI Installation
        run: aws --version

      # Upload Release Assets to Cloudflare R2
      - name: Upload Assets to Cloudflare R2
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          echo "Starting upload to Cloudflare R2..."
          PLATFORM=""
          case "${{ matrix.os }}" in
            macos-latest)
              PLATFORM="macos"
              ;;
            ubuntu-latest)
              PLATFORM="linux"
              ;;
            windows-latest)
              PLATFORM="windows"
              ;;
          esac
          
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          
          aws s3 cp out/make/ s3://$BUCKET_NAME/$PLATFORM/$VERSION/ --recursive --acl public-read --endpoint-url --region us-east-1 $R2_ENDPOINT --debug